### ISSUE TITLE
se2 등 작은 기기에서 화면 잘림

### ISSUE THREAD

**Issue by 2unbini** [42Caterpie/Lets-Git-It-iOS#63]
## 🐞 버그 설명
se2에서 화면 잘리는 현상 발생
![image](https://user-images.githubusercontent.com/75126613/152679630-6d07bb03-7779-4e4c-815f-bad54c1adbba.jpeg)

## 📝 todo
- [ ] 작은 기기에서도 제대로 보일 수 있도록 수정

**Comment by hekang42** [comment]
iPad에서도 위처럼 나오네요 내일 스크롤 뷰로 전체적으로 바꿔볼께요 !
