### ISSUE TITLE
[FEAT] 위젯 아이디어 !

### ISSUE THREAD

**Issue by jinbekim** [42Caterpie/Lets-Git-It-iOS#70]
## 📌  Feature Issue

위젯에 잔디밭을 그냥 보여줘도 될것 같지만,
혹시 잔디밭 대신 식물이 자라는 모습을 보여 주실 수 있나요? 그래서 하루 끊기거나 3일 끊겨서 물을 못주면 식물이 시드는 거죠.!

대신 기존에 심은 잔디를 토대로 하는게 아니라 새로 목표를 설정하면 그때부터 기록한 잔디로 식물이 성장하게
그래서 이미 오랜기간 잔디를 심은 사람도 새롭게 목표를 부여할 수 있도록 해주면 좋을 것 같습니다.

나중에는 캐릭터나 다른 성장을 확인할 수 있는 무언가로 대채할 수 있으면 좋겠네요.
그래서 나중에는 과금을 통해서 그 무언가를 뽑을 수 있는거죠!

## 📝  To-do

- [ ] 단계별 식물 이미지
- [ ] 시든 모습의 식물
- [ ] 고생과 노력

**Comment by hekang42** [comment]
<img width="144" alt="image" src="https://user-images.githubusercontent.com/42266439/152747118-2f7b6c1f-a469-4530-a71b-098a5f8dbf79.png">

**Comment by hekang42** [comment]
DM 보냈습니다.
