### ISSUE TITLE
iPhone SE에서 Contribution box 가로 화면이 카드 뷰를 벗어나는 문제

### ISSUE THREAD

**Issue by 2unbini** [42Caterpie/Lets-Git-It-iOS#71]
## 🐞 버그 설명
iPhone SE에서 Contribution box 가로 화면이 잘리는 문제
![KakaoTalk_Photo_2022-02-08-18-01-00](https://user-images.githubusercontent.com/75126613/152953357-15e38443-069b-41a6-be1b-61cb37dc8503.jpeg)

## 📝 todo
- [ ] 현재 표시되는 가로 contribution 개수 이하의 디바이스에 대응

**Comment by hekang42** [comment]
기기 가로 사이즈에 비율로 계산해서 넣어야겠네요 !
